---
title: "Regression Model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadData}
library(olsrr)
ACT_Data <- read.csv("../Manipulated Data/ACT Data 2017-18.csv")
ACT_Data <- ACT_Data[, -1]
ACT_Data$zip <- ACT_Data$Zipcode
ACT_Data <- ACT_Data[, -2]
GraduationRate <- read.csv("../Manipulated Data/Graduation Rate.csv")
GraduationRate$GraduationRate <- as.numeric(as.character(GraduationRate$GraduationRate))
GraduationRate$zip <- GraduationRate$zipcode
GraduationRate <- GraduationRate[, -1]
Demographic <- read.csv("../Manipulated Data/Demographic.csv")
Demographic <- Demographic[, -c(2, 3, 4, 5)]
Demographic$zip <- Demographic$zip.code
Demographic <- Demographic[, -1]
EmployeeEducation <- read.csv("../Manipulated Data/EmployeeEducationData.csv")
EmployeeEducation$zip <- EmployeeEducation$zip.code
EmployeeEducation <- EmployeeEducation[, -c(1, 2, 3, 4, 5, 6, 7)]
MeanIncome <- read.csv("../Manipulated Data/mean_income.csv")
MeanIncome$Mean.income <- as.numeric(as.character(MeanIncome$Mean.income))
MeanIncome$zip <- MeanIncome[, 1]
MeanIncome <- MeanIncome[, -1]
PrivateSchoolRatio <- read.csv("../Manipulated Data/PublicPrivateSchool.csv")
PrivateSchoolRatio$Private.Ratio <- as.numeric(as.character(PrivateSchoolRatio$Private.Ratio))
PrivateSchoolRatio$zip <- PrivateSchoolRatio$Zipcode
PrivateSchoolRatio <- PrivateSchoolRatio[, -c(1, 2, 3, 4, 5, 6, 7)]

```

```{r mergeDatasets}

ACT <- merge(Demographic, ACT_Data, by = "zip", all = TRUE)
ACT <- merge(ACT, EmployeeEducation, by = "zip", all = TRUE)
ACT <- merge(ACT, MeanIncome, by = "zip", all = TRUE)
ACT <- merge(ACT, PrivateSchoolRatio, by = "zip", all = TRUE)


ACTWithoutDemographic <- merge(ACT, EmployeeEducation, by = "zip", all = TRUE)
ACTWithoutDemographic <- merge(ACT, MeanIncome, by = "zip", all = TRUE)
ACTWithoutDemographic <- merge(ACT, PrivateSchoolRatio, by = "zip", all = TRUE)
 


temp <- ACT$zip
temp <- ACT$zip[which(duplicated(temp))]
for(zip in temp) {
  counter <- 1
  for(dup in which(ACT$zip == zip)) {
    ACT$zip[dup] <- paste(ACT$zip[dup], "-", counter)
    counter <- counter + 1
  }
}
rownames(ACT) <- ACT$zip
ACT <- ACT[, -1]


Grad <- merge(Demographic, GraduationRate, by = "zip", all = TRUE)
Grad <- merge(Grad, EmployeeEducation, by = "zip", all = TRUE)
Grad <- merge(Grad, MeanIncome, by = "zip", all = TRUE)
Grad <- merge(Grad, PrivateSchoolRatio, by = "zip", all = TRUE)
rownames(Grad) <- Grad$zip
Grad <- Grad[, -1]

```

```{r linearRegression}
lm.fit.ACT <- lm(ACT ~ ., data = ACT)
summary(lm.fit.ACT)
##plot(lm.fit.ACT)
#ols_coll_diag(lm.fit.ACT)
ols_vif_tol(lm.fit.ACT)
ols_eigen_cindex(lm.fit.ACT)
#ols_correlations(lm.fit.ACT)
#ols_regress(lm.fit.ACT)
#ols_plot_diagnostics(lm.fit.ACT)
lm.fit.ACT.temp <- lm(ACT ~ ACT + Assoc.Ratio + Bachelor.Ratio + Master.Ratio + Prof.Degree.Ratio + 
                        Doctor.Ratio + Mean.income + Private.Ratio, data = ACT)
summary(lm.fit.ACT.temp)
anova(lm.fit.ACT.temp, lm.fit.ACT)


lm.fit.Grad <- lm(GraduationRate ~ ., data = Grad)

lm.fit.Gradtemp <- lm(GraduationRate ~ GraduationRate + Assoc.Ratio + Bachelor.Ratio + Master.Ratio + Prof.Degree.Ratio + Doctor.Ratio + Mean.income + Private.Ratio, data = Grad)
#ols_vif_tol(lm.fit.Grad)
summary(lm.fit.Grad)
summary(lm.fit.Gradtemp)

anova(lm.fit.Gradtemp, lm.fit.Grad)
#plot(lm.fit.Grad)
```

